name: Deploy to GitHub pages branch
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install deps
        run: |
          npm install
      - name: Build
        run: |
          npm run-script build:esbuild
      - name: Prepare for deploy
        run: |
          rm -rf targetdir
          mkdir -p targetdir
          mv dist index.html styles/ favicon.ico targetdir/
      - name: Deployy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: targetdir